# Generated by Django 4.2.4 on 2023-09-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparkmodel',
            options={'ordering': ('id',)},
        ),
    ]
