# Generated by Django 4.2.5 on 2023-09-06 14:47

import core.services.upload_avatar_service
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_avatar_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='avatar',
        ),
        migrations.CreateModel(
            name='AvatarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.services.upload_avatar_service.upload_avatar)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='users.profilemodel')),
            ],
            options={
                'db_table': 'profile_avatars',
            },
        ),
    ]
