# Generated by Django 4.2.5 on 2023-09-07 07:51

import core.services.upload_avatar_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profilemodel_avatar_avatarmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarmodel',
            name='image',
            field=models.ImageField(upload_to=core.services.upload_avatar_service.upload_avatar),
        ),
    ]
